configs:
  yolo11n-object365-pen:
    description: 使用yolo11n_object365模型检测钢笔
    model_path: /home/unitree/lxy_arm/ultralytics/yolo11n_object365.pt
    object_class_id: 54
    object_name: 钢笔
  yolo11n-object365-phone:
    description: 使用yolo11n_object365模型检测手机
    model_path: /home/unitree/lxy_arm/ultralytics/yolo11n_object365.pt
    object_class_id: 67
    object_name: 手机
  yolo11n-object365-book:
    description: 使用yolo11n_object365模型检测书本
    model_path: /home/unitree/lxy_arm/ultralytics/yolo11n_object365.pt
    object_class_id: 18
    object_name: 书本
  yolo26n-objv1-150-pen:
    description: 使用yolo26n-objv1-150模型检测钢笔
    model_path: /home/unitree/lxy_arm/ultralytics/yolo26n-objv1-150.pt
    object_class_id: 51
    object_name: 钢笔
  yolov8n-book:
    description: 使用yolov8n检测书
    model_path: /home/unitree/lxy_arm/ultralytics/yolov8n.pt
    object_class_id: 73
    object_name: book
  yolov8s-book:
    description: 使用yolov8s检测书
    model_path: /home/unitree/lxy_arm/ultralytics/yolov8s.pt
    object_class_id: 73
    object_name: book
  yolov8m-book:
    description: 使用yolov8m检测书
    model_path: /home/unitree/lxy_arm/ultralytics/yolov8m.pt
    object_class_id: 73
    object_name: book
  yolov8l-book:
    description: 使用yolov8l检测书
    model_path: /home/unitree/lxy_arm/ultralytics/yolov8l.pt
    object_class_id: 73
    object_name: book
current_config: yolov8m-book
